In [14]:
import tensorflow as tf
import tensorflow_datasets as tfds


In [15]:
mnist_data = tfds.load("fashion_mnist")
for item in mnist_data:
 print(item)

test
train


In [16]:
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))


<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>


In [17]:
for item in mnist_train.take(1):
 print(type(item))
 print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


In [18]:
for item in mnist_train.take(1):
 print(type(item))
 print(item.keys())
 print(item['image'])
 print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


the image is a 28 × 28 array of values from
0–255 representing the pixel intensity. The label will be output as tf.Tensor(2,
shape=(), dtype=int64), indicating that this image is class 2 in the dataset.

In [19]:
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels),(test_images, test_labels) = mnist.load_data()


In [20]:
training_images.shape, training_labels.shape, test_images.shape, test_labels.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [21]:
training_images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [22]:
(training_images, training_labels),(test_images, test_labels) = tfds.as_numpy(tfds.load('fashion_mnist',
                                                                                          split = ['train', 'test'],
                                                                                          batch_size=-1,
                                                                                          as_supervised=True))


Using tfds.as_numpy in
the call to tfds.load causes them to be returned as Numpy arrays. Specifying
batch_size=-1 gives us all of the data, and as_supervised=True ensures we get
tuples of (input, label) returned.

In [23]:
training_images.shape, training_labels.shape, test_images.shape, test_labels.shape

((60000, 28, 28, 1), (60000,), (10000, 28, 28, 1), (10000,))

In [24]:
training_images

array([[[[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        ...,

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]]],


       [[[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [  0],
         [  0]],

        [[  0],
         [  0],
         [  0],
         ...,
         [  0],
         [

In [25]:
training_images = training_images / 255.0
test_images = test_images / 255.0

the input data shape is (28,28,1)

In [26]:
model = tf.keras.models.Sequential([
 tf.keras.layers.Flatten(input_shape=(28,28,1)),
 tf.keras.layers.Dense(128, activation=tf.nn.relu),
 tf.keras.layers.Dropout(0.2),
 tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])


In [29]:
model.fit(training_images, training_labels, epochs=10, validation_data=(test_images,test_labels))

Epoch 1/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2810 - accuracy: 0.8950 - val_loss: 0.3446 - val_accuracy: 0.8808
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2753 - accuracy: 0.8965 - val_loss: 0.3324 - val_accuracy: 0.8823
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2708 - accuracy: 0.8985 - val_loss: 0.3361 - val_accuracy: 0.8839
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2665 - accuracy: 0.8996 - val_loss: 0.3341 - val_accuracy: 0.8851
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2624 - accuracy: 0.9016 - val_loss: 0.3394 - val_accuracy: 0.8828
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2563 - accuracy: 0.9032 - val_loss: 0.3472 - val_accuracy: 0.8806
Epoch 7/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2533 - accuracy: 0.9044 - val_loss: 0.3519 - val_accuracy:

In [30]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 0.3401 - accuracy: 0.8853


[0.34007248282432556, 0.8852999806404114]